### ISSUE TITLE
Use Case-k formátuma, elképzelések

### ISSUE THREAD

**Issue by davidbolla** [bme-db-lab/szglab5-test#1]
levelezés felvétele issue-nak
Kérdésem az volt, hogy mi az elvárás, illetve mellékeltem egy megírt mintát, amit gherkinszerű nyelvben írtam, néhány olyan résszel, amit korábbi munkahelyeimen használtam.

A válasz @gbence -től picit kivonatolva (amit kihagytam, az félreértés volt, vagy nem releváns):

1) Ha "gherkin" akkor tartsuk magunkat ezekhez:

* https://cucumber.io/docs/reference
* http://docs.behat.org/en/v2.5/guides/1.gherkin.html

2) Azt javaslom, hogy egyszerű use-case-eket írjatok, először ne legyen
gond az, hogy semmi sem helyes és nem tudjátok őket futtatni. Inkább
gyűjtsetek össze felesleges, redundáns eseteket, mintsem kihagyjatok
valami olyasmit, amire számítunk.

3) Ha konkrét példát szeretnél tőlem látni:

~~~
Feature: managing Questions

  Admin users and gurus should be able to manage Questions
  using the Client application.

Background:
  Given an accessible backend API
  And an admin user called "Admin"
  And 3 Questions in "SQL" topic
  Given I own "Admin" user's API key

Scenario: listing Questions
  When I GET /api/1/questions
  Then I should get 3 items

Scenario: adding a new Question
  When I POST /api/1/questions with JSON body
    """
    {question: "X", topic: "SQL"}
    """
  Then I should get OK response

**Comment by davidbolla** [comment]
@gbence részemről a kérdés, hogy akkor szerdára a beugrós részre kellenek a use case-k és a tesztek, ugye?
köszönöm

**Comment by gbence** [comment]
@bkopy igen.  Én köszönöm. :)
